title: Ashish Ameria
logo: files/Circular_photo30.png
description: Data Analyst|Additive Mfg|Mech Engg
#show_downloads: true
theme: jekyll-remote-theme
title: [The title of your site]
description: [A short description of your site's purpose]
